### List messages
GET http://localhost:3000/auth/

###CREAte new message
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email":"rom1.chenard@gmail.com",
    "password": "azerty"
}

###CREAte new message
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email":"rom1.chenard@gmail.com",
    "password": "azerty"
}

### signout
POST http://localhost:3000/auth/signout

###WHO AMI I
GET http://localhost:3000/auth/whoami
content-type: application/json

###GET particular id
GET http://localhost:3000/auth/5

###GET every users with email
GET http://localhost:3000/auth?email=rom.chenard@gmail.com




###GET particular message
GET http://localhost:3000/auth/4

###Delete user by id
DELETE http://localhost:3000/auth/323

###Update user by id
PATCH http://localhost:3000/auth/35
content-type: application/json

{
    "email":"xxxxxx@gmail.com",
    "password": "azerty123"
}