### List messages
GET http://localhost:3000/auth/

###CREAte new message
POST http://localhost:3000/messages
content-type: application/json

{
    "email":"rom.chenard@gmail.com",
    "password": "azerty"
}

###GET particular message
GET http://localhost:3000/messages/68