### Create new report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "price": 50000,
    "model": "corolla",
    "year": 1980,
    "mileage": 120000,
    "lng": 0,
    "lat": 0
}